// Makes the two committed clips and src/clips.ts from them: `node packages/testing/scripts/make-clips.mjs`.
// Needs espeak-ng and ffmpeg on the machine that runs it (the clips are committed, so nothing else needs them).
// Each clip is espeak-ng's speech of its transcript, 16 kHz mono 16-bit PCM WAV.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const CLIPS = [
  { key: 'english', file: 'english.wav', voice: 'en-us', lang: 'en-US', transcript: 'Please read me the first chapter' },
  { key: 'greek', file: 'greek.wav', voice: 'el', lang: 'el-GR', transcript: 'Θέλω να ακούσω τον πρώτο ψαλμό' },
];

mkdirSync(join(root, 'clips'), { recursive: true });
let out = `// GENERATED by scripts/make-clips.mjs from clips/*.wav: do not edit. Each clip is espeak-ng's speech of its transcript,\n// 16 kHz mono 16-bit PCM, as base64 so it travels inside a Playwright init script.\n`;
out += `import type { Clip } from './mic.js';\n\n`;
for (const c of CLIPS) {
  const raw = join(root, 'clips', `raw-${c.file}`);
  execFileSync('espeak-ng', ['-v', c.voice, '-s', '150', '-w', raw, c.transcript]);
  const wav = join(root, 'clips', c.file);
  execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-i', raw, '-ar', '16000', '-ac', '1', '-c:a', 'pcm_s16le', '-af', 'silenceremove=start_periods=1:start_threshold=-50dB,areverse,silenceremove=start_periods=1:start_threshold=-50dB,areverse', wav]);
  execFileSync('rm', [raw]);
  const b64 = readFileSync(wav).toString('base64');
  out += `export const ${c.key}: Clip = {\n  name: '${c.key}',\n  lang: '${c.lang}',\n  transcript: '${c.transcript}',\n  wavBase64:\n    '${b64}',\n};\n\n`;
}
writeFileSync(join(root, 'src', 'clips.ts'), out.trimEnd() + '\n');
